### PR TITLE
Fix "Internal Server Error" when no pronunciation is found, fix missing translation

### LINKED ISSUE #22: Internal server error
when i prompt from swahili to english, i get an internal server error

erro song transl

### PR DESCRIPTION
**Pull request by dsnsgithub**
The API route fails when it can't find a pronunciation for a translation.

Request URL: `https://t.song.work/api?text=你好&from=auto&to=en`
```json
{"statusCode":500,"error":"Internal Server Error","message":"Cannot read properties of null (reading 'innerText')"}
```

With my fix, it no longer errors when a pronunciation is not found, and the pronunciation keys are removed from the result.

Request URL: `http://localhost:8999/api?text=你好&from=auto&to=en`
```json
{"result":"Hello","from":{"pronunciation":"Nǐ hǎo"},"translations":{"interjection":[{"translation":"Hi!","reversedTranslations":["嗨!","你好!"],"frequency":"common"},{"translation":"Hallo!","reversedTranslations":["你好!"],"frequency":"rare"},{"translation":"Hello!","reversedTranslations":["你好!","喂!"],"frequency":"common"}]}}
```

I also updated the result `targetSelector` to fix missing translations that occur when there is no pronunciation.

closes https://github.com/Songkeys/Translateer/issues/22

### CODE REVIEW

File: src/parser/parser.ts [hunk 1]
```diff
@@ -117,7 +117,7 @@ export const parsePage = async (
 	let pronunciation = "";
 	do {
 		// const targetSelector = `span[data-language-for-alternatives=${to}]`;
-		const targetSelector = `span[lang=${to}]`;
+		const targetSelector = `.ryNqvb`;
```
Comment (songkeys) [inline src/parser/parser.ts]: This class name is automatically randomly generated when bundling the website. Every time Google Translate publishes a new version, it will be changed. We need a better selector that is more likely to be stable.

**Review by songkeys — CHANGES_REQUESTED** [review]

File: src/parser/parser.ts (hunk 1 above)
Comment (dsnsgithub) [reply src/parser/parser.ts]: In my newest commit I changed the targetSelector to `span[lang=${to}] > span > span` which should hopefully be more stable.

**Comment by dsnsgithub** [comment]
I also pushed a new commit that fixes the word "undefined" from appearing in the pronunciation.

Request URL: `https://t.song.work/api?text=你好&from=zh-CN&to=en`
```json
{"result":"Hello","pronunciation":"undefined","from":{"pronunciation":"Nǐ hǎo","suggestions":[{"text":"你好","translation":" "},{"text":"你好 很高兴收到你的来信","translation":" "},{"text":"你好 你过得怎么样","translation":" "}]},"translations":{"interjection":[{"translation":"Hi!","reversedTranslations":["嗨!","你好!"],"frequency":"common"},{"translation":"Hallo!","reversedTranslations":["你好!"],"frequency":"rare"},{"translation":"Hello!","reversedTranslations":["你好!","喂!"],"frequency":"common"}]}}
```

Request URL: `http://localhost:8999/api?text=你好&from=zh-CN&to=en`
```json
{"result":"Hello","from":{"pronunciation":"Nǐ hǎo","suggestions":[{"text":"你好","translation":" "},{"text":"你好 很高兴收到你的来信","translation":" "},{"text":"你好 你过得怎么样","translation":" "}]},"translations":{"interjection":[{"translation":"Hi!","reversedTranslations":["嗨!","你好!"],"frequency":"common"},{"translation":"Hallo!","reversedTranslations":["你好!"],"frequency":"rare"},{"translation":"Hello!","reversedTranslations":["你好!","喂!"],"frequency":"common"}]}}
```

**Comment by dsnsgithub** [comment]
The original `span[lang=${to}]` only works sometimes, and fails when the detected/input language is the same as the output. The selector would try to find the text in the input box and return an empty string.

This request would give Internal Server Error under `t.song.work`, but using my modified version with `span[lang=${to}]` as the targetSelector with URL `http://localhost:8999/api?text=no&from=auto&to=en`
```json
{"result":"","from":{"pronunciation":"nō"},"definitions":{"article":[{"definition":"not any.","example":"there is no excuse"}],"exclamation":[{"definition":"used to give a negative response.","example":"“Is anything wrong?” “No.”","synonyms":{"common":["no indeed absolutely not most certainly not of course not under no circumstances by no means not at all negative never not really no thanks nae"],"informal":["nope nah not on your life no way no fear not on your nelly no siree naw"],"archaic":["nay"]}}],"adverb":[{"definition":"not at all; to no extent.","example":"they were no more able to perform the task than I was"}],"noun":[{"definition":"a negative answer or decision, as in voting.","example":"he was unable to change his automatic yes to a no"},{"definition":"variant spelling of Noh."}],"abbreviation":[{"definition":"number.","example":"No. 27"}],"":[{"definition":"the chemical element nobelium."}]}}
```

Using `span[lang=${to}] > span > span` fixes this problem.
```json
{"result":"no","from":{"pronunciation":"nō"},"definitions":{"article":[{"definition":"not any.","example":"there is no excuse"}],"exclamation":[{"definition":"used to give a negative response.","example":"“Is anything wrong?” “No.”","synonyms":{"common":["no indeed absolutely not most certainly not of course not under no circumstances by no means not at all negative never not really no thanks nae"],"informal":["nope nah not on your life no way no fear not on your nelly no siree naw"],"archaic":["nay"]}}],"adverb":[{"definition":"not at all; to no extent.","example":"they were no more able to perform the task than I was"}],"noun":[{"definition":"a negative answer or decision, as in voting.","example":"he was unable to change his automatic yes to a no"},{"definition":"variant spelling of Noh."}],"abbreviation":[{"definition":"number.","example":"No. 27"}],"":[{"definition":"the chemical element nobelium."}]}}
```

**Review by songkeys — APPROVED** [review]

**Comment by songkeys** [comment]
Thank you so much for this fix! ❤️
